[package]
name = "hydrogen"
version = "0.1.0"
authors = ["Nathan Sizemore <nathanrsizemore@gmail.com>"]
description = "Presence system framework"
repository = "https://github.com/nathansizemore/hydrogen"
readme = "README.md"
keywords = ["presence"]
license = "MPL 2.0"

[lib]
name = "hydrogen"
crate-type = ["staticlib", "rlib"]

# From crates.io
[dependencies]
libc = "*"
rand = "*"
num_cpus = "*"
fern = "*"
log = "*"
time = "*"

# From git
[dependencies.epoll]
git = "https://github.com/nathansizemore/epoll"

[dependencies.simple-stream]
git = "https://github.com/nathansizemore/simple-stream"
