[package]
name = "server"
version = "0.1.0"
authors = ["Nathan Sizemore <nathanrsizemore@gmail.com>"]

[dependencies]
log = "^0.3.6"
libc = "^0.2.10"
env_logger = "^0.3.3"
simple-stream = "^0.9.6"
hydrogen = { path = "../../" }
